version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

jobs:
  deploy:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - run: echo $CIRCLE_SHA1
      - run: echo $CIRCLE_BRANCH
      - run: echo << pipeline.parameters.GHA_Meta >>
  noop:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - run: echo "noop"

workflows:
  version: 2
  deploy:
    when: << pipeline.parameters.GHA_Action >>
    jobs:
      - deploy
  # Dummy job to avoid "All Workflows have been filtered from this Pipeline."
  # error being thrown on GitHub status checks.
  #
  # See: https://github.com/CircleCI-Public/circleci-cli/issues/577
  noop:
    unless: << pipeline.parameters.GHA_Action >>
    jobs:
      - noop
